name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
env:
  PYTHON_VERSION: "3.12.8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-python-dependency
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .
          
      - name: install playwright dependency
        run: |
          playwright install chromium

      - name: run-script
        run: |
          python script.py
